sudo: required

services:
  - docker

install:
  - docker build webapp/ -t $DOCKER_USERNAME/toolchain-webapp

script:
  - echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/toolchain-webapp

branches:
  only:
    - master

